### ISSUE TITLE
Reduction factor for small groups

### ISSUE THREAD

**Issue by kacper-swietkowski** [vizik24/fattermap#1]
# Reduction factor: safer with small groups
    reduction_factor = 0.9 if group_size <= 4 else 1.2

    # Calculate risk
    risk = (slope_factor * aspect_factor * weather_factor * wind_factor) / reduction_factor
    return risk
    
    here the risk will be higher for a smaller group, you'll end up with a reduction factor of 0.9 for a group of size 4 or below, and the risk divided by 0.9 will be higher! Are you sure?

**Comment by vizik24** [comment]
Thanks for your comment, I have adjusted it for now, but definitely something to tinker with.
