### ISSUE TITLE
Aspect risk assessment incorrect in southern hemisphere

### ISSUE THREAD

**Issue by castoridaee** [vizik24/fattermap#2]
Aspect factor adjustment should check for hemisphere before setting it (just a simple longitude check).

`    # Aspect factor: riskier on north/east slopes in Northern Hemisphere
    if aspect in ["north", "east"]:
        aspect_factor = 1.3
    else:
        aspect_factor = 1
`

**Comment by vizik24** [comment]
You're correct. As I understand it, the method was developed for the European Alps. The program has not been validated with real world data yet. This should be mentioned in the readme.
